name: Test and build docker image

on:
  push:
    branches:
      - '**'

jobs:
  TestCode:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install -U poetry
          poetry install

      - name: Run tests
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "cronbackup"
          use-black: false
          use-yapf: false
          use-isort: false
          use-docformatter: false
          use-pycodestyle: false
          use-autopep8: false
          use-pydocstyle: false
          use-mypy: false
          use-pylint: false
          use-flake8: true
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false
          extra-black-options: ""
          extra-yapf-options: ""
          extra-isort-options: ""
          extra-docformatter-options: ""
          extra-pycodestyle-options: ""
          extra-pydocstyle-options: ""
          extra-mypy-options: ""
          extra-pylint-options: ""
          extra-flake8-options: ""
          extra-mccabe-options: ""
          extra-radon-options: ""
          extra-rstcheck-options: ""
          extra-manifest-options: ""
          extra-pyroma-options: ""

#       - name: Upload flake8 report
#         uses: actions/upload-artifact@v3
#         with:
#           name: flake8-report
#           path: flake8-report

  DockerBuildPush:
    runs-on: ubuntu-latest

    needs: TestCode
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Branch Environment
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          pull: true
          context: .
          push: true
          tags: ghcr.io/bmarcin/cronbackup:${{ env.BRANCH }}, ghcr.io/bmarcin/cronbackup:latest
          cache-from: type=registry,ref=ghcr.io/bmarcin/cronbackup:latest
          cache-to: type=inline
          build-args: |
            BRANCH=${{ env.BRANCH }}